/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTLCard;

import static BTLCard.FormMain.customer;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author khaia
 */
public class FormNapTien extends javax.swing.JFrame {

    private ConnectApplet connectApplet;
    private JFrame frame;
    static byte counter;
    static boolean ts_du = false;
    static Customer customer;
    private boolean input = false;

    final static byte Wallet_CLA = (byte) 0xB0;
    final static byte VERIFY = (byte) 0x20;
    final static byte CREDIT = (byte) 0x30;
    final static byte DEBIT = (byte) 0x40;
    final static byte GET_BALANCE = (byte) 0x50;
    final static byte UNBLOCK = (byte) 0x60;

    /**
     * Creates new form FormNapTien
     */
    public FormNapTien() {
        initComponents();
        customer = new Customer();
        connectApplet = new ConnectApplet();
        setLocationRelativeTo(null);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtnt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Nạp tiền");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nhập số tiền:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        if (checkcard() == false) {
//            if (checkpin() == true) {
//                naptien();
//            } else {
//                JOptionPane.showMessageDialog(null, "Mã PIN sai. Vui lòng nhập lại.");
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Thẻ của bạn đã bị khóa. Tìm cách mở khóa đi.");
//        }
    }//GEN-LAST:event_jButton1ActionPerformed
//    private boolean checkcard() {
//        short datalen = 1; //do dai du lieu gui vao applet
//        short maxdata_expect = 1;//du lieu nhan mong doi (Le)
//        byte[] cmd = {(byte) 0x80, (byte) 0x14, (byte) 0x00, (byte) 0x00};
//        connectApplet.setTheAPDUCommands(cmd);
//        connectApplet.setTheDataLengthShort(datalen);
//        byte[] data_u = {(byte) 0};
//        connectApplet.setTheDataIn(data_u);
//        connectApplet.setExpctShortLength(maxdata_expect);
//        setTheCommandAPDUOnGUI2(cmd, data_u, datalen, maxdata_expect);
//        connectApplet.exchangeTheAPDUWithSimulator();
//        connectApplet.decodeStatus();
//        setTheResponseAPDUOnGUI(maxdata_expect);
//        byte[] dataOut = connectApplet.decodeDataOut();//du lieu nhan ve tu applet
//        if (dataOut[0] == (byte) 0x00) {//chưa bị khóa, Ok
//            return false;
//        } else {
//            return true;
//        }
//    }
//
//    //gửi mã PIN vào applet để applet check (OK)
//    private boolean checkpin() {
//        String pin = Arrays.toString(txtpin.getPassword());
//        short datalen = (short) pin.length(); //do dai du lieu gui vao applet
//        short maxdata_expect = 1;//du lieu nhan mong doi (Le)
//        byte[] cmd = {(byte) 0x80, (byte) 0x16, (byte) 0x00, (byte) 0x00};
//        connectApplet.setTheAPDUCommands(cmd);
//        connectApplet.setTheDataLengthShort(datalen);
//        byte[] data_u = pin.getBytes();
//        connectApplet.setTheDataIn(data_u);
//        connectApplet.setExpctShortLength(maxdata_expect);
//        setTheCommandAPDUOnGUI2(cmd, data_u, datalen, maxdata_expect);
//        connectApplet.exchangeTheAPDUWithSimulator();
//        connectApplet.decodeStatus();
//        setTheResponseAPDUOnGUI(maxdata_expect);
//        byte[] dataOut = connectApplet.decodeDataOut();//du lieu nhan ve tu applet
//        if (dataOut[0] == (byte) 0x00) {//đúng mã PIN
//            return true;
//        } else {
//            return false;
//        }
//    }
//    public void naptien() {
//        System.err.println("Credit");
//        //credit
//        byte lengthDataField = 1;
//        byte maxDataBytesExpected = 0;
//        byte instParamtr1 = 0;
//        byte instParamtr2 = 0;
//
//        byte[] cmnds_c = {Wallet_CLA, CREDIT, instParamtr1, instParamtr2};
//        connectApplet.setTheAPDUCommands(cmnds_c);
//        connectApplet.setTheDataLength(lengthDataField);
//        try {
//            byte[] data_c = {(byte) Integer.parseInt(txtnt.getText())};
//            connectApplet.setTheDataIn(data_c);
//            connectApplet.setExpctdByteLength(maxDataBytesExpected);
//            setTheCommandAPDUOnGUI(cmnds_c, data_c, lengthDataField, maxDataBytesExpected);
//            JOptionPane.showMessageDialog(this, "Nap tien thanh cong");
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(frame, "PLEASE ENTER A VALID INPUT.");
//            JOptionPane.showMessageDialog(this, "Nap tien khong thanh cong");
//        }
//        connectApplet.exchangeTheAPDUWithSimulator();
//        connectApplet.decodeStatus();
//        setTheResponseAPDUOnGUI(maxDataBytesExpected);
//    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormNapTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormNapTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormNapTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormNapTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormNapTien().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.List list1;
    private javax.swing.JTextField txtnt;
    // End of variables declaration//GEN-END:variables
}
